create table form_drafts (
  id bigint generated by default as identity primary key,
  reference_number text not null unique,
  school_name text not null,
  school_id text,
  report_data jsonb not null default '{}',
  status text not null default 'Draft',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index idx_form_drafts_school_name on form_drafts (school_name);
create index idx_form_drafts_status on form_drafts (status);
create index idx_form_drafts_created_at on form_drafts (created_at);
