create table bullying_reports (
  id bigint generated by default as identity primary key,
  reference_number text not null,
  submitted_at timestamptz not null default now(),
  school_name text not null,
  division text not null default 'Ormoc City Division LRP',
  module text not null,
  category text,
  report_data jsonb not null default '{}',
  prepared_by jsonb,
  validated_by jsonb,
  status text not null default 'pending',
  webhook_sent_at timestamptz,
  created_at timestamptz not null default now()
);

create index idx_bullying_reports_status on bullying_reports (status);
create index idx_bullying_reports_reference on bullying_reports (reference_number);
create index idx_bullying_reports_created_at on bullying_reports (created_at);