create table registered_ips (
  id bigint generated by default as identity primary key,
  email text not null,
  ip_address text not null,
  created_at timestamptz not null default now(),
  unique (email, ip_address)
);

create index idx_registered_ips_email on registered_ips (email);