-- 1. Create division_schools table
CREATE TABLE IF NOT EXISTS public.division_schools (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT UNIQUE NOT NULL,
  district TEXT NOT NULL,
  psds TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.division_schools ENABLE ROW LEVEL SECURITY;

-- 3. RLS Policies (everyone authenticated can read schools)
DROP POLICY IF EXISTS "Allow authenticated read division_schools" ON public.division_schools;
CREATE POLICY "Allow authenticated read division_schools"
ON public.division_schools FOR SELECT
TO authenticated, anon
USING (true);

-- 4. Seed all Ormoc City Division schools
INSERT INTO public.division_schools (district, psds, name) VALUES
('District 1', 'Emma A. Porcadilla', 'OCCS'),
('District 1', 'Emma A. Porcadilla', 'OC SPED IS (Elem)'),
('District 1', 'Emma A. Porcadilla', 'OC SPED IS (Sec)'),
('District 1', 'Emma A. Porcadilla', 'Alta Vista ES'),
('District 1', 'Emma A. Porcadilla', 'Mahayag ES'),
('District 1', 'Emma A. Porcadilla', 'Patag ES'),
('District 1', 'Emma A. Porcadilla', 'Donghol IS (Elem)'),
('District 1', 'Emma A. Porcadilla', 'Donghol IS (Sec)'),
('District 1', 'Emma A. Porcadilla', 'OC Night HS'),
('District 1', 'Emma A. Porcadilla', 'OC Senior HS'),
('District 2', 'Ma. Jereza C. Matiga', 'Ipil CS'),
('District 2', 'Ma. Jereza C. Matiga', 'Camp Downes ES'),
('District 2', 'Ma. Jereza C. Matiga', 'Can-adieng ES'),
('District 2', 'Ma. Jereza C. Matiga', 'Can-untog ES'),
('District 2', 'Ma. Jereza C. Matiga', 'DC Rivilla ES'),
('District 2', 'Ma. Jereza C. Matiga', 'Hugpa ES'),
('District 2', 'Ma. Jereza C. Matiga', 'LY Palou ES'),
('District 2', 'Ma. Jereza C. Matiga', 'Mabini ES'),
('District 2', 'Ma. Jereza C. Matiga', 'Macabug ES'),
('District 2', 'Ma. Jereza C. Matiga', 'Mahayahay ES'),
('District 2', 'Ma. Jereza C. Matiga', 'Quezon Jr. ES'),
('District 2', 'Ma. Jereza C. Matiga', 'Sumangga ES'),
('District 2', 'Ma. Jereza C. Matiga', 'San Antonio IS (Elem)'),
('District 2', 'Ma. Jereza C. Matiga', 'San Antonio IS (Sec)'),
('District 2', 'Ma. Jereza C. Matiga', 'Ipil National HS'),
('District 3', 'Elvira De Leon', 'Linao CS'),
('District 3', 'Elvira De Leon', 'Alegria-Batuan ES'),
('District 3', 'Elvira De Leon', 'JICA Lao ES'),
('District 3', 'Elvira De Leon', 'Naungan ES'),
('District 3', 'Elvira De Leon', 'Punta ES'),
('District 3', 'Elvira De Leon', 'Tambulilid ES'),
('District 3', 'Elvira De Leon', 'Lao IS (Elem)'),
('District 3', 'Elvira De Leon', 'Lao IS (Sec)'),
('District 3', 'Elvira De Leon', 'Linao NHS'),
('District 4', 'Melisa R. Bughao', 'Cogon CS'),
('District 4', 'Melisa R. Bughao', 'Biliboy ES'),
('District 4', 'Melisa R. Bughao', 'Cabintan ES'),
('District 4', 'Melisa R. Bughao', 'Nasunogan ES'),
('District 4', 'Melisa R. Bughao', 'Salvacion ES'),
('District 4', 'Melisa R. Bughao', 'San Pablo ES'),
('District 4', 'Melisa R. Bughao', 'Sto. Niño ES'),
('District 4', 'Melisa R. Bughao', 'Tongonan ES'),
('District 4', 'Melisa R. Bughao', 'Cabintan NHS'),
('District 4', 'Melisa R. Bughao', 'PGBNHS'),
('District 4', 'Melisa R. Bughao', 'Salvacion NHS'),
('District 5', 'Uldarico N. Bojos Jr.', 'Liloan CS'),
('District 5', 'Uldarico N. Bojos Jr.', 'Airport ES'),
('District 5', 'Uldarico N. Bojos Jr.', 'Balion ES'),
('District 5', 'Uldarico N. Bojos Jr.', 'Leondoni ES'),
('District 5', 'Uldarico N. Bojos Jr.', 'Libertad ES'),
('District 5', 'Uldarico N. Bojos Jr.', 'Licuma ES'),
('District 5', 'Uldarico N. Bojos Jr.', 'Manlilinao ES'),
('District 5', 'Uldarico N. Bojos Jr.', 'RM Tan ES'),
('District 5', 'Uldarico N. Bojos Jr.', 'JGNHS'),
('District 5', 'Uldarico N. Bojos Jr.', 'Liloan NHS'),
('District 6', 'Elena Angelita C. Sios-E', 'Valencia CS'),
('District 6', 'Elena Angelita C. Sios-E', 'Cagbuhangin ES'),
('District 6', 'Elena Angelita C. Sios-E', 'Concepcion ES'),
('District 6', 'Elena Angelita C. Sios-E', 'Dayhagan ES'),
('District 6', 'Elena Angelita C. Sios-E', 'Hibunaon ES'),
('District 6', 'Elena Angelita C. Sios-E', 'Juaton ES'),
('District 6', 'Elena Angelita C. Sios-E', 'Maticaa ES'),
('District 6', 'Elena Angelita C. Sios-E', 'T. Aviles ES'),
('District 6', 'Elena Angelita C. Sios-E', 'Maticaa NHS'),
('District 6', 'Elena Angelita C. Sios-E', 'Valencia NHS'),
('District 7', 'Gina Labiste', 'San Jose CS'),
('District 7', 'Gina Labiste', 'Cabatoan ES'),
('District 7', 'Gina Labiste', 'Catmon ES'),
('District 7', 'Gina Labiste', 'Dr. H. Serafica ES'),
('District 7', 'Gina Labiste', 'Guintiguian ES'),
('District 7', 'Gina Labiste', 'L. Cabahug ES'),
('District 7', 'Gina Labiste', 'Monterico IS (Elem)'),
('District 7', 'Gina Labiste', 'Monterico IS (Sec)'),
('District 7', 'Gina Labiste', 'Sabang Bao ES'),
('District 7', 'Gina Labiste', 'GBLNHS'),
('District 7', 'Gina Labiste', 'RCSMNHS'),
('District 8', 'Rhoda Dinoy', 'Dolores CS'),
('District 8', 'Rhoda Dinoy', 'Bagong ES'),
('District 8', 'Rhoda Dinoy', 'Cabaon-an ES'),
('District 8', 'Rhoda Dinoy', 'Luna ES'),
('District 8', 'Rhoda Dinoy', 'Magaswe ES'),
('District 8', 'Rhoda Dinoy', 'Milagro ES'),
('District 8', 'Rhoda Dinoy', 'Nueva Vista IS (Elem)'),
('District 8', 'Rhoda Dinoy', 'Nueva Vista IS (Sec)'),
('District 8', 'Rhoda Dinoy', 'Gaas IS (Elem)'),
('District 8', 'Rhoda Dinoy', 'Gaas IS (Sec)'),
('District 8', 'Rhoda Dinoy', 'Liberty IS (Elem)'),
('District 8', 'Rhoda Dinoy', 'Liberty IS (Sec)'),
('District 8', 'Rhoda Dinoy', 'Lake Danao IS (Elem)'),
('District 8', 'Rhoda Dinoy', 'Lake Danao IS (Sec)'),
('District 8', 'Rhoda Dinoy', 'Dolores NHS'),
('District 9', 'Marylyn S. Tagalog', 'Curva CS'),
('District 9', 'Marylyn S. Tagalog', 'Domonar ES'),
('District 9', 'Marylyn S. Tagalog', 'Esperanza ES'),
('District 9', 'Marylyn S. Tagalog', 'Green Valley ES'),
('District 9', 'Marylyn S. Tagalog', 'Inaad ES'),
('District 9', 'Marylyn S. Tagalog', 'Margen ES'),
('District 9', 'Marylyn S. Tagalog', 'San Juan ES'),
('District 9', 'Marylyn S. Tagalog', 'San Vicente ES'),
('District 9', 'Marylyn S. Tagalog', 'VL Villasencio ES'),
('District 9', 'Marylyn S. Tagalog', 'Mas-in IS (Elem)'),
('District 9', 'Marylyn S. Tagalog', 'Mas-in IS (Sec)'),
('District 9', 'Marylyn S. Tagalog', 'Margen NHS'),
('District 10', 'Caroline M. Magno', 'San Isidro IS (Elem)'),
('District 10', 'Caroline M. Magno', 'San Isidro IS (Sec)'),
('District 10', 'Caroline M. Magno', 'Bagong Buhay ES'),
('District 10', 'Caroline M. Magno', 'Doña Feliza Mejia ES'),
('District 10', 'Caroline M. Magno', 'NOCNHS'),
('District 10', 'Caroline M. Magno', 'OC Sr. Sports SHS')
ON CONFLICT (name) DO UPDATE 
SET district = EXCLUDED.district, psds = EXCLUDED.psds;
